---
kafka_version: "3.9.2"
kafka_scala_version: "2.13"

kafka_user: kafka
kafka_group: kafka

kafka_install_dir: /opt/kafka
kafka_data_dir: /var/lib/kafka/data
kafka_config_dir: /etc/kafka

kafka_download_url: "https://archive.apache.org/dist/kafka/3.9.2/kafka_2.13-3.9.2.tgz"

kafka_broker_port: 9092
kafka_controller_port: 9093

kafka_controller_quorum_voters: "1@172.31.27.172:9093,2@172.31.20.48:9093"

# Same KRaft cluster ID must be used on both brokers.
kafka_cluster_id: "MkU3OEVBNTcwNTJENDM2Qk"

kafka_java_package: openjdk-21-jre-headless
